### ISSUE TITLE
What is the correct way to import pimp?

### ISSUE THREAD

**Issue by vchouksey** [janvanrijn/openml-pimp#1]
Hello,

What is the correct way to import pimp? getting an error while calling.
<img width="627" alt="screen shot 2018-01-11 at 14 48 45" src="https://user-images.githubusercontent.com/6507341/34828730-c114fe4e-f6de-11e7-8c7b-bee512c21d9f.png">

**Comment by janvanrijn** [comment]
it's this repo:

https://github.com/automl/ParameterImportance

2018-01-11 14:50 GMT+01:00 Vishal Chouksey <notifications@github.com>:

**Comment by vchouksey** [comment]
Please close this issue, this issue has been resolved by installing PIMP. 
<img width="733" alt="screen shot 2018-01-11 at 18 32 09" src="https://user-images.githubusercontent.com/6507341/34839390-bea5b5ae-f701-11e7-923f-bcadf7e00275.png">
